"""
hiringAssistant_router.py
--------------------------
FastAPI routes for the hiring assistant.

Endpoints:
  POST /hiring/chat/text            — text message turn
  POST /hiring/chat/voice           — voice input → Whisper → GPT → TTS audio out
  POST /hiring/otp/send             — trigger OTP email
  POST /hiring/otp/verify           — validate OTP code
  POST /hiring/resume/upload        — multipart PDF upload, triggers finalization
  DELETE /hiring/audio/{session_id} — frontend calls this on session close to delete TTS audio from S3
  GET  /hiring/debug/session/{id}   — inspect full Redis session (DISABLE IN PRODUCTION)
"""

import os
import uuid
import time
import logging
import random
import string
from typing import Optional
import httpx
from fastapi import APIRouter, File, Form, HTTPException, UploadFile, Depends
from fastapi.responses import JSONResponse

from app.utils.cache_manager import hiring_cache
from app.utils.upload_to_bucket import (
    upload_file_object_to_s3,
    delete_s3_keys_batch,
    delete_s3_prefix,
)
from app.services.hiringAssistant.hiringAssistant import (
    backfill_candidate_fields_from_history,
    process_chat,
    process_voice,
    finalize_resume,
)
from app.services.hiringAssistant.hiringAssistant_schema import (
    ChatResponse,
    ChatTextRequest,
    DebugSessionResponse,
    OTPSendResponse,
    OTPVerifyRequest,
    ResumeUploadResponse,
    SessionStep,
)
from app.core.config import settings

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/hiring", tags=["Hiring Assistant"])

# External OTP service — set these in your .env
OTP_BACKEND_SEND_URL = os.getenv("OTP_BACKEND_SEND_URL")      # e.g. https://auth.yourbackend.com/otp/send
OTP_BACKEND_VERIFY_URL = os.getenv("OTP_BACKEND_VERIFY_URL")  # e.g. https://auth.yourbackend.com/otp/verify
OTP_BACKEND_TIMEOUT = 10  # seconds
# OTP expiry in seconds
OTP_TTL_SECONDS = 600  # 10 minutes


# ============================================================
#  Dependency: validate session exists
# ============================================================

def require_session(session_id: str) -> dict:
    """FastAPI dependency — raises 404 if session not in Redis."""
    session = hiring_cache.get_session(session_id)
    if not session:
        raise HTTPException(
            status_code=404,
            detail=f"Session '{session_id}' not found or has expired. Please start a new session.",
        )
    return session


# ============================================================
#  POST /hiring/chat/text
# ============================================================

@router.post("/chat/text", response_model=ChatResponse, summary="Send a text message")
async def chat_text(request: ChatTextRequest):
    """
    Main text chat endpoint. The frontend calls this on every candidate message.

    - On the very first message, pass `job_details` so the AI knows the role context.
    - `session_id` must be generated by the frontend (UUID) and sent on every request.
    - Returns `action: show_file_input` when interview is done (frontend shows upload widget).
    - Returns `action: close_session` with `payload` after resume upload is complete.
    """
    try:
        response = await process_chat(
            session_id=request.session_id,
            user_message=request.message,
            job_details=request.job_details,
            generate_audio=False,
        )
        return response
    except Exception as e:
        logger.error(f"chat_text error [{request.session_id}]: {e}", exc_info=True)
        raise HTTPException(status_code=500, detail="Internal server error")


# ============================================================
#  POST /hiring/chat/voice
# ============================================================

@router.post("/chat/voice", response_model=ChatResponse, summary="Send a voice message")
async def chat_voice(
    session_id: str = Form(...),
    audio: UploadFile = File(..., description="Raw audio file (webm, mp4, wav, m4a, mp3)"),
    job_details: Optional[str] = Form(None, description="JSON string of job details (first message only)"),
):
    """
    Voice input endpoint.
    1. Receives raw audio from frontend.
    2. Transcribes via OpenAI Whisper.
    3. Runs the same pipeline as /chat/text.
    4. Generates TTS audio for the AI reply.
    5. Returns { message, audio_url, action }.

    The frontend should play `audio_url` when it is present.
    """
    import json as _json

    try:
        audio_bytes = await audio.read()
        jd = None
        if job_details:
            try:
                jd = _json.loads(job_details)
            except Exception:
                logger.warning(f"Could not parse job_details JSON for session {session_id}")

        response = await process_voice(
            session_id=session_id,
            audio_bytes=audio_bytes,
            job_details=jd,
        )
        return response
    except Exception as e:
        logger.error(f"chat_voice error [{session_id}]: {e}", exc_info=True)
        raise HTTPException(status_code=500, detail="Internal server error")


# # ============================================================
# #  POST /hiring/otp/send
# # ============================================================

# @router.post("/otp/send", response_model=OTPSendResponse, summary="Send OTP to candidate email")
# async def otp_send(session_id: str = Form(...)):
#     """
#     Triggered by frontend once the AI has collected the candidate's email address.
#     Generates a 4-digit OTP, stores it in Redis, and sends it via email.

#     In production: plug in your email provider (SES, SendGrid, etc.) in _send_otp_email().
#     """
#     session = hiring_cache.get_session(session_id)
#     if not session:
#         raise HTTPException(status_code=404, detail="Session not found")

#     # Recover contact fields from the stored chat history if the session snapshot is stale.
#     if not session.get("candidate", {}).get("email"):
#         session = backfill_candidate_fields_from_history(session)
#         hiring_cache.save_session(session_id, session)

#     email = session.get("candidate", {}).get("email")
#     if not email:
#         raise HTTPException(status_code=400, detail="Email not yet collected in session")

#     # Generate OTP
#     otp = "".join(random.choices(string.digits, k=4))
#     expires_at = time.time() + OTP_TTL_SECONDS

#     session["otp"] = otp
#     session["otp_expires"] = expires_at
#     hiring_cache.save_session(session_id, session)

#     # Send the OTP email
#     sent = await _send_otp_email(email, otp)
#     if not sent:
#         raise HTTPException(status_code=500, detail="Failed to send OTP email")

#     logger.info(f"OTP sent to {email} for session {session_id}")
#     return OTPSendResponse(
#         success=True,
#         message=f"Verification code sent to {email}",
#     )


# # ============================================================
# #  POST /hiring/otp/verify
# # ============================================================

# @router.post("/otp/verify", summary="Verify the OTP code")
# async def otp_verify(request: OTPVerifyRequest):
#     """
#     Frontend calls this when the candidate submits their 4-digit code.
#     Returns { "validated": true } on success, advances session step to otp_verified.
#     Returns 400 on wrong code or expiry.
#     """
#     session = hiring_cache.get_session(request.session_id)
#     if not session:
#         raise HTTPException(status_code=404, detail="Session not found")

#     stored_otp = session.get("otp")
#     otp_expires = session.get("otp_expires", 0)

#     if not stored_otp:
#         raise HTTPException(status_code=400, detail="No OTP found for this session")

#     if time.time() > otp_expires:
#         raise HTTPException(status_code=400, detail="OTP has expired. Please request a new one.")

#     if request.code.strip() != stored_otp:
#         raise HTTPException(status_code=400, detail="Invalid verification code")

#     # Clear OTP and advance step
#     session["otp"] = None
#     session["otp_expires"] = None
#     session["step"] = SessionStep.otp_verified
#     hiring_cache.save_session(request.session_id, session)

#     logger.info(f"OTP verified for session {request.session_id}")
#     return {"validated": True}

# ============================================================
#  POST /hiring/otp/send
# ============================================================
 
@router.post("/otp/send", response_model=OTPSendResponse, summary="Send OTP to candidate email via external backend")
async def otp_send(session_id: str = Form(...)):
    """
    Delegates OTP sending to your external auth backend.
    Reads the candidate's email from the Redis session, then calls OTP_BACKEND_SEND_URL.
 
    Your external backend handles: OTP generation, email delivery, expiry.
    We store nothing OTP-related in Redis.
 
    Set in .env:
      OTP_BACKEND_SEND_URL=https://auth.yourbackend.com/otp/send
    """
    session = hiring_cache.get_session(session_id)
    if not session:
        raise HTTPException(status_code=404, detail="Session not found")
 
    email = session.get("candidate", {}).get("email")
    if not email:
        raise HTTPException(status_code=400, detail="Email not yet collected in this session")

    if not settings.OTP_CHECKER:
        # Generate random 4-digit OTP
        mock_otp = "".join(random.choices(string.digits, k=4))
        session["otp"] = mock_otp
        session["otp_expires"] = time.time() + OTP_TTL_SECONDS
        hiring_cache.save_session(session_id, session)
        logger.info(f"[DEV] Mock OTP generated for {email}: {mock_otp} (session {session_id})")
        return OTPSendResponse(
            success=True,
            message=f"Verification code sent to {email}",
        )

    if not OTP_BACKEND_SEND_URL:
        raise HTTPException(status_code=500, detail="OTP_BACKEND_SEND_URL not configured in .env")
 
    try:
        async with httpx.AsyncClient(timeout=OTP_BACKEND_TIMEOUT) as http:
            response = await http.post(
                OTP_BACKEND_SEND_URL,
                json={"email": email},           # adjust payload shape to match your backend
            )
            response.raise_for_status()
    except httpx.TimeoutException:
        raise HTTPException(status_code=504, detail="OTP service timed out. Please try again.")
    except httpx.HTTPStatusError as e:
        logger.error(f"OTP send failed for {email}: {e.response.status_code} {e.response.text}")
        raise HTTPException(status_code=502, detail="OTP service returned an error. Please try again.")
    except Exception as e:
        logger.error(f"OTP send unexpected error: {e}", exc_info=True)
        raise HTTPException(status_code=500, detail="Could not reach OTP service.")
 
    logger.info(f"OTP send delegated to external backend for {email} (session {session_id})")
    return OTPSendResponse(
        success=True,
        message=f"Verification code sent to {email}",
    )
 
 
# ============================================================
#  POST /hiring/otp/verify
# ============================================================
 
@router.post("/otp/verify", summary="Verify OTP code via external backend")
async def otp_verify(request: OTPVerifyRequest):
    """
    Sends the candidate's code to your external backend for verification.
 
    On success (external returns true):
      - Advances session step to otp_verified
      - Returns { "validated": true }
 
    On failure (wrong code / expired):
      - Returns 400 with a clear message
      - Session stays at otp_pending so the candidate can retry or request resend
 
    Frontend flow:
      Wrong code  → show error, let candidate retype (call this endpoint again)
      Resend      → call POST /hiring/otp/send again with the same session_id
 
    Set in .env:
      OTP_BACKEND_VERIFY_URL=https://auth.yourbackend.com/otp/verify
    """
    session = hiring_cache.get_session(request.session_id)
    if not session:
        raise HTTPException(status_code=404, detail="Session not found")
 
    email = session.get("candidate", {}).get("email")
    if not email:
        raise HTTPException(status_code=400, detail="No email found in session")
 
    if not settings.OTP_CHECKER:
        stored_otp = session.get("otp")
        otp_expires = session.get("otp_expires", 0)
        
        if not stored_otp:
            raise HTTPException(status_code=400, detail="No OTP requested.")
            
        if time.time() > otp_expires:
            raise HTTPException(status_code=400, detail="OTP has expired. Please request a new one.")
            
        if request.code.strip() != stored_otp:
            raise HTTPException(status_code=400, detail="Invalid verification code.")
            
        # Success
        session["step"] = SessionStep.otp_verified
        session["otp"] = None
        session["otp_expires"] = None
        hiring_cache.save_session(request.session_id, session)
        logger.info(f"[DEV] Mock OTP verified for session {request.session_id}")
        return {"validated": True}

    if not OTP_BACKEND_VERIFY_URL:
        raise HTTPException(status_code=500, detail="OTP_BACKEND_VERIFY_URL not configured in .env")
 
    # Call external backend to verify
    try:
        async with httpx.AsyncClient(timeout=OTP_BACKEND_TIMEOUT) as http:
            response = await http.post(
                OTP_BACKEND_VERIFY_URL,
                json={
                    "email": email,
                    "code": request.code.strip(),   # adjust field names to match your backend
                },
            )
 
            # If backend returns 4xx, it means wrong code or expired — not a server error
            if response.status_code == 400 or response.status_code == 422:
                detail = _extract_error_message(response)
                raise HTTPException(status_code=400, detail=detail or "Invalid or expired verification code.")
 
            response.raise_for_status()
            body = response.json()
 
    except HTTPException:
        raise   # re-raise our own 400s
    except httpx.TimeoutException:
        raise HTTPException(status_code=504, detail="OTP service timed out. Please try again.")
    except httpx.HTTPStatusError as e:
        logger.error(f"OTP verify error: {e.response.status_code} {e.response.text}")
        raise HTTPException(status_code=502, detail="OTP service returned an error.")
    except Exception as e:
        logger.error(f"OTP verify unexpected error: {e}", exc_info=True)
        raise HTTPException(status_code=500, detail="Could not reach OTP service.")
 
    # Check the response body — your backend may return { "validated": true } or { "success": true }
    # Adjust the key name below to match your backend's actual response shape
    is_valid = (
        body.get("validated") is True
        or body.get("success") is True
        or body.get("verified") is True
        or body.get("valid") is True
    )
 
    if not is_valid:
        raise HTTPException(status_code=400, detail="Invalid or expired verification code. Please try again.")
 
    # Advance session step
    session["step"] = SessionStep.otp_verified
    hiring_cache.save_session(request.session_id, session)
 
    logger.info(f"OTP verified via external backend for session {request.session_id}")
    return {"validated": True}
 
 
def _extract_error_message(response: httpx.Response) -> Optional[str]:
    """Try to pull a human-readable error from the external backend's response body."""
    try:
        body = response.json()
        return (
            body.get("message")
            or body.get("detail")
            or body.get("error")
            or body.get("msg")
        )
    except Exception:
        return None

# ============================================================
#  POST /hiring/resume/upload
# ============================================================

@router.post("/resume/upload", response_model=ResumeUploadResponse, summary="Upload candidate resume")
async def resume_upload(
    session_id: str = Form(...),
    resume: UploadFile = File(..., description="Candidate resume PDF"),
):
    """
    Receives the resume PDF, uploads to S3 under resumes/{session_id}.pdf,
    then calls finalize_resume() which:
      - Stores resume URL in session
      - Generates interview summary
      - Builds final candidate payload
      - Wipes Redis session
      - Deletes TTS audio from S3

    The response from this endpoint is the FINAL ChatResponse with:
      action: close_session
      payload: { all candidate data for your other backend }
    """
    session = hiring_cache.get_session(session_id)
    if not session:
        raise HTTPException(status_code=404, detail="Session not found")

    if session.get("step") not in (SessionStep.resume_upload, SessionStep.complete):
        raise HTTPException(
            status_code=400,
            detail=f"Resume upload not expected at step: {session.get('step')}",
        )

    # Validate file type
    content_type = resume.content_type or ""
    filename = resume.filename or ""
    if "pdf" not in content_type.lower() and not filename.lower().endswith(".pdf"):
        raise HTTPException(status_code=400, detail="Only PDF files are accepted")

    # Upload to S3
    s3_key = f"resumes/{session_id}.pdf"
    file_bytes = await resume.read()

    from io import BytesIO
    result = upload_file_object_to_s3(
        file_object=BytesIO(file_bytes),
        object_name=s3_key,
    )

    if not result.get("success"):
        raise HTTPException(status_code=500, detail=f"Resume upload failed: {result.get('message')}")

    resume_url = result["url"]
    logger.info(f"Resume uploaded for session {session_id}: {resume_url}")

    # Finalize: build payload, cleanup, close session
    final_response = await finalize_resume(session_id, resume_url)
    return final_response


# ============================================================
#  DELETE /hiring/audio/{session_id}
# ============================================================
 
@router.delete("/audio/{session_id}", summary="Delete TTS audio files for a session from S3")
async def delete_session_audio(session_id: str):
    """
    Called by frontend when the session is closed (after receiving close_session action).
 
    Deletes all TTS audio files that were generated during the session.
    Two strategies used in order:
      1. If Redis session still exists: use the tracked tts_turns list (precise)
      2. If Redis is already wiped: fallback to S3 prefix scan (audio/tts/{session_id}_*)
 
    Frontend should call this endpoint:
      - After receiving action: close_session in the chat response
      - Or when the user closes/navigates away from the chat window
 
    Returns:
      { "deleted": N, "errors": [] }
    """
    deleted_count = 0
    errors = []
 
    # Strategy 1: use tracked keys from Redis if session still alive
    tts_keys = hiring_cache.get_tts_keys(session_id)
    if tts_keys:
        logger.info(f"Deleting {len(tts_keys)} tracked TTS keys for session {session_id}")
        result = delete_s3_keys_batch(tts_keys)
        deleted_count = result.get("deleted_count", 0)
        errors = result.get("errors", [])
    else:
        # Strategy 2: Redis already wiped — scan S3 by prefix
        logger.info(f"No Redis keys found for {session_id}, falling back to S3 prefix scan")
        result = delete_s3_prefix(f"audio/tts/{session_id}_")
        deleted_count = result.get("deleted_count", 0)
        errors = result.get("errors", [])
 
    # Also wipe Redis session if it's somehow still there
    if hiring_cache.session_exists(session_id):
        hiring_cache.delete_session(session_id)
 
    logger.info(f"Audio cleanup complete for session {session_id}: {deleted_count} files deleted")
    return {
        "success": len(errors) == 0,
        "session_id": session_id,
        "deleted": deleted_count,
        "errors": errors,
    }
 
 

# ============================================================
#  GET /hiring/debug/session/{session_id}
# ============================================================

@router.get(
    "/debug/session/{session_id}",
    response_model=DebugSessionResponse,
    summary="[DEBUG] Inspect full Redis session — DISABLE IN PRODUCTION",
)
async def debug_session(session_id: str):
    """
    Returns the full session blob from Redis including:
    - Current step
    - All messages
    - Questions queue with answered/remaining counts
    - Internal scores (DO NOT expose this in production)
    - TTS audio S3 keys

    Use this in Swagger UI (/docs) or Postman to inspect session state during development.
    """
    if os.getenv("ENVIRONMENT", "development") == "production":
        raise HTTPException(
            status_code=403,
            detail="Debug endpoint disabled in production",
        )

    exists = hiring_cache.session_exists(session_id)
    session_data = hiring_cache.raw_session_for_debug(session_id) if exists else None

    return DebugSessionResponse(
        session_id=session_id,
        session=session_data,
        exists=exists,
    )


# ============================================================
#  GET /hiring/health
# ============================================================

@router.get("/health", summary="Health check for hiring assistant service")
async def health():
    redis_ok = hiring_cache._connected
    return {
        "status": "ok" if redis_ok else "degraded",
        "redis": "connected" if redis_ok else "disconnected",
    }


# # ============================================================
# #  Internal: OTP email sender — plug in your provider here
# # ============================================================

# async def _send_otp_email(email: str, otp: str) -> bool:
#     """
#     Send OTP to candidate email.
#     Replace the body of this function with your email provider (AWS SES, SendGrid, etc.)

#     Example with AWS SES (boto3):
#         import boto3
#         ses = boto3.client('ses', region_name='eu-north-1')
#         ses.send_email(
#             Source='noreply@yourplatform.com',
#             Destination={'ToAddresses': [email]},
#             Message={
#                 'Subject': {'Data': 'Your verification code'},
#                 'Body': {'Text': {'Data': f'Your 4-digit code is: {otp}\\nExpires in 10 minutes.'}},
#             },
#         )
#     """
#     try:
#         # TODO: replace with real email provider
#         logger.info(f"[DEV] OTP for {email}: {otp}")
#         # Simulate success for now
#         return True
#     except Exception as e:
#         logger.error(f"Email send failed for {email}: {e}")
#         return False